### ISSUE TITLE
Add bare metal CI testing

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-boot#180] opened 2018-10-16 17:29 UTC
Pending the DRP port, want to run tests on physical servers.

We have build VM on Build OpenStack instance that manages physical servers.

Rebuild VM and then run tests.

A slightly modified version of CI tests.

**Comment by spisarski** [comment] 2018-11-16 21:29
Duplicate of #147

**Closed by spisarski** 2018-11-16 21:29 UTC
